server:
  port: 8083
spring:
    datasource:
         driver-class-name: com.mysql.jdbc.Driver
         password: root
         url: jdbc:mysql://localhost:3306/order
         username: root
    jpa:
         show-sql: true
         hibernate:
            ddl-auto: update
    thymeleaf:
         prefix: classpath:/templates/
         cache: false
         suffix: .html
         encoding: utf-8
         mode: HTML5
